# Numpy & Arrays

Numpy is a general purpose array-processing package.
It provides a high performance multidimensional array object & tools for working with these arrays.
It is the fundamental package for scientific computing with python.

Array is a data structure that stores values of same datatype .
In python this is the main difference between arays & lists.
While python lists can contain values corresponding to different data types. 

In [107]:
import numpy as np
list = [1,2,3,4,5]
arr = np.array(list) # array is an inbuilt function
arr

array([1, 2, 3, 4, 5])

In [108]:
type(arr)

numpy.ndarray

In [109]:
arr.shape #returns the dimensions of the array , for 1-D array it returns the element only

(5,)

In [110]:
list1 = [1,2,3,4,5]
list2 = [2,3,4,5,6]
list3 = [3,4,5,6,7]
arr = np.array([list1 , list2 , list3]) # Creates a multi-dimensional array
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [111]:
arr.shape # returns (3,5) here 3 is the no of rows/index and 5 is the no. of columns ( Form of 3X3 Matrix)

(3, 5)

In [112]:
arr.reshape(5,3) # rebuilds the array in the form it is given ( Form of 5X3 Matrix)  

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

NOTE:- Reshaping doesn't updates the values and Matrix forms to the original array

In [113]:
arr[:,:] # returns the full array

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [114]:
arr[1:,1:] # returns tha array from the given index to the end

array([[3, 4, 5, 6],
       [4, 5, 6, 7]])

In [115]:
arr[:3,:3] # returns the array form the starting to the given index

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [116]:
arr = np.arange(0 ,10) #returns all the integers between 0 an 10 ( 10 >>> exclusive)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [117]:
arr = np.arange(0 , 10 , 2) #returns all the integer from 0 to 10 by an interval gap of 2 ( 10 >>> exclusive)
print(arr)

[0 2 4 6 8]


In [118]:
arr = np.linspace(0 , 10 , 50) #returns 50 floating point numbers between 0 and 10
print(arr)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


Copy Function

In [119]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[3:] = 100 # assigns this value to all the elements from index 3 to the end
print(arr)

[  1   2   3 100 100 100 100 100 100]


In [120]:
arr1 = arr.copy() # creates a new array "arr1" and copies all the elements from arr to arr1
print(arr1)

[  1   2   3 100 100 100 100 100 100]


In [121]:
val = 3
arr < val # returns True or False as per the condition given { For eg:- 1<3 True , 2<3 True , 100<3 False , ............So On!!!!}

array([ True,  True, False, False, False, False, False, False, False])

In [122]:
arr[arr<val] # returns the values or elements as per the condition given

array([1, 2])

Using arange() and reshape() functions simultaneously

In [123]:
arr1 = np.arange(0 , 15).reshape(3,5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [124]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([1,2,3,4,5])
arr * arr1 #returns the product of all the elements of both the arrays

array([ 1,  4,  9, 16, 25])

In [125]:
arr = np.ones(10 , dtype = float) # updates the array by 4 elements all with the same value "1." ("." is for the floating point )  Default value is float
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [126]:
arr = np.ones(5 , dtype = int) # updates the array by 4 elements all with the same value "1" (No "."  for the integers value )
print(arr)

[1 1 1 1 1]


In [127]:
x = np.random.rand() # returns random floating point values between 0 and 1 ( The values change in every run)
print(x)

0.4298873468623732


In [128]:
x = np.random.rand(3,3) # creates a 3X3 multi-dimensional array with random floating nos. between 0 and 1
print(x)

[[0.50158774 0.18135693 0.81151482]
 [0.80626536 0.8356778  0.32797502]
 [0.74218469 0.91754589 0.85160361]]


In [150]:
np.random.randint(0 , 100 ,size=25).reshape(5,5) # returns 5X5 Matrix of integers  and the fomrat is {start = 0 , stop = 100 , size_of_array = 25}

array([[55, 51, 62, 77, 45],
       [13, 38, 21, 31, 86],
       [73, 63, 42, 59, 19],
       [56, 70, 76,  7, 85],
       [46, 88, 65, 62, 22]])

In [153]:
np.random.random_sample([4,4]) # returns random floats in the interval [ 0.0 , 1.0] {Semi-Open-interval} [4,4] represents the reshape format

array([[0.11931463, 0.38559456, 0.20062528, 0.05174595],
       [0.52003377, 0.53620236, 0.49739803, 0.96213262],
       [0.1458808 , 0.48043343, 0.08952422, 0.0819418 ],
       [0.66876034, 0.01140167, 0.24326144, 0.51437979]])